# -*- coding: utf-8 -*-
"""houseprice _pred

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rwtaSvg9mPku2SpIXg7AyAtrpXkYzavY
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

data=pd.read_csv("/content/Housing.csv")
data

data.shape

data.isnull().sum()

x=data[['area','bedrooms','bathrooms']]
y=data['price']

x

y

x

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=23)

from sklearn.linear_model import LinearRegression
ols=LinearRegression()
ols.fit(x_train,y_train)
prediction=ols.predict(x_test)

from sklearn.metrics import mean_squared_error as mse
print('OLS',mse(y_test,prediction))
print('OLS',np.sqrt(mse(y_test,prediction)))

from sklearn.metrics import mean_squared_error, r2_score

from sklearn.linear_model import SGDRegressor
lr=SGDRegressor()
lr.fit(x_train,y_train)
prediction2=lr.predict(x_test)

print('Linear Regression test',mse(y_test,prediction2))
print('Linear Regression train',mse(y_train,lr.predict(x_train)))
print('Linear Regression test',np.sqrt(mse(y_test,prediction2)))



